### ISSUE TITLE
Share back the json-joy benchmarking trace?

### ISSUE THREAD

**Issue by josephg** [streamich/json-joy#277]
Hi! I saw you created an editing trace as part of your blog post that lives here:

https://github.com/streamich/json-joy/tree/master/benchmarks/data/text-editing-traces

Mind if I add it to my editing-traces repository for others to use & run on our own algorithms?

**Comment by streamich** [comment]
Hey! I was planning to open a pull request. I'm working on two more traces, I will submit once they are ready.
