### ISSUE TITLE
Running CRDT editing trace benchmarks

### ISSUE THREAD

**Issue by TeemuKoivisto** [streamich/json-joy#345]
Hey, awesome work 👍!

I somehow stumbled upon your blog post https://jsonjoy.com/blog/list-crdt-benchmarks which got me curious if `yrs` was still broken. I couldn't get the benchmarks to run anymore so I copy-pasted your code and put them here: https://github.com/TeemuKoivisto/crdt-nodejs-editing-trace-benchmarks

Hope you're fine with that, I did not get `json-joy` however to run anymore since apparently the API had changed since the last time you ran the benchmarks.

```ts
       model.api.root('')
       const str = model.api.str([])
```

Those parts appear broken. Also Automerge keeps crashing which probably was happening before as well. And it seems `yrs` got fixed since then which is nice.

**Comment by streamich** [comment]
Hey, yes, `yrs` was fixed after that blog post.
