### ISSUE TITLE
Error when make patch flush in nodejs

### ISSUE THREAD

**Issue by antablack** [streamich/json-joy#462]
I am trying to run this example https://jsonjoy.com/libs/json-joy-js/json-crdt/guide/concurrent-users in nodejs v18.18.2 but, I got this error ReferenceError: CustomEvent is not defined.
![Screenshot 2023-11-28 at 11 03 15 AM](https://github.com/streamich/json-joy/assets/22205647/fd763988-74ff-41d4-9cbe-2548df9a5df0)

In nodejs is an experimental feature even for the latest version https://nodejs.org/api/events.html#class-customevent (Node.js v21.2.0).
 JSON-JOY version (11.5.0).

**Comment by streamich** [comment]
Also, currently the `CustomEvent` is used only when you use `model.api` on the server, if you use just `model.applyPatch()` the `CustomEvent` is not needed.

**Comment by streamich** [comment]
`CustomEvent` API has been removed.
