### ISSUE TITLE
[BUG]: Issue with reserved filenames on Windows

### ISSUE THREAD

**Issue by rokln** [streamich/json-joy#482]
While installing `json-joy` I encountered an issue when attempting to clean up my `node_modules` folder.

Upon further investigation, as the title indicates, reserved filenames are being used. Specifically, the path `json-joy/src/json-crdt/nodes/con` includes `CON`, a filename that is reserved in Windows. Consequently, this results in folders that cannot be deleted due to Windows' handling of such cases. It is unclear if the issue extends to other paths.

To reproduce this issue on Windows 10:
1. `mkdir testfolder`
2. `cd testfolder`
3. `npm init`
4. `npm install json-joy`
5. Attempting to delete the created `node_modules` folder fails.

Expected Result:
The `node_modules` folder should delete without issue.

Actual Result:
Deletion of the `node_modules` folder fails due to the usage of Windows' reserved filename, `CON`, in the dependency path."

Proposed Solution:
Change the CON filename in the json-joy/src/json-crdt/nodes directory to a non-reserved filename.

For reference, here are all reserved filenames on Windows:
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9.

**Comment by pvdstel** [comment]
Hi, would it be possible to also backport this fix to v9.9 as `9.9.1`? This is affecting Webpack's development server, through [webpack-dev-middleware](https://www.npmjs.com/package/webpack-dev-middleware) which depends on [memfs](https://www.npmjs.com/package/memfs) which depends on this package `^9.2.0`. Publishing a patch release should resolve the issue without requiring downstream upgrades.
