### ISSUE TITLE
Why are 'child' and 'container' always undefined in JsonNode?

### ISSUE THREAD

**Issue by 534254884** [streamich/json-joy#640]
export interface JsonNode<View = unknown> extends Identifiable {
    name(): string;
    view(): View;
    children(callback: (node: JsonNode) => void): void;
    child?(): JsonNode | undefined;
    container(): JsonNode | undefined;
    api: undefined | unknown;
}

**Comment by streamich** [comment]
They are not always `undefined`. I think they are defined in `val` and `vec` nodes.
