### ISSUE TITLE
Getting started page is not up to date

### ISSUE THREAD

**Issue by macmillen** [streamich/json-joy#686]
On the getting started page it says I'm able to import from multiple targets like this:
``` ts
  import { deepEqual } from "json-joy/es2020/json-equal";
```

Unfortunately it doesn't work and I get this error:
```
Cannot find module 'json-joy/es2020/json-equal' or its corresponding type declarations
```

https://jsonjoy.com/libs/json-joy-js/getting-started

**Comment by macmillen** [comment]
Apparently `withLogicalClock` is also deprecated but still in the docs. This should also be updated

**Comment by streamich** [comment]
Yes, it will be updated soon. Please use `/lib` instead of `/es2020`. And `Model.create()` instead of `Model.withLogicalClock()`.

**Comment by hanayashiki** [comment]
When?
