### ISSUE TITLE
CBOR - import not working

### ISSUE THREAD

**Issue by anrl** [streamich/json-joy#701]
I am having difficulty in finding the CBOR encoder/decoder. 

The following statement in the documentation does not work. 

import {CborEncoder} from 'json-joy/es2020/json-pack/cbor/CborEncoder';
import {CborDecoder} from 'json-joy/es2020/json-pack/cbor/CborDecoder';

Any ideas?

**Comment by streamich** [comment]
JSON codecs have been moved to [`@jsonjoy.com/json-pack`](https://github.com/jsonjoy-com/json-pack) repository.

```
npm install @jsonjoy.com/json-pack
```
