### ISSUE TITLE
customization to have Map, BigNumber

### ISSUE THREAD

**Issue by anymos** [streamich/json-joy#777]
Hello:

What would be the best course of action if I want to have that part working :

`let _map=new Map();
    _map.set('key',{
        o:1
    })

        const pojo = {
            id: 123,
            foo: 'bar',
            tags: ['a', 'b', 'c'],
            bn:new BigNumber(3),
            map:_map
        };
        const encoder = new JsonEncoder(new Writer());
        const encoded = encoder.encode(pojo);
        const decoder = new JsonDecoder();
        const decoded = decoder.read(encoded);

        console.log(`json:decoded:`,decoded);`

bn and map are null

**Comment by streamich** [comment]
You can extends the `JsonEncoder` and `JsonDecoder` classes.

In `JsonEncoder` overwrite the `encodeUnknown` method:

```js
class MyEncoder extends JsonEncoder {
  encodeUnknown(value) {
    if (typeof value === 'bigint') {
      return String(value);
    }
    return super.encodeUnknown(value);
  }
}
```

In the `JsonDecoder` overwrite the `readAny` method:

```js
  public readAny(): unknown {
    this.skipWhitespace();
    const reader = this.reader;
    // Try to decode a bigint using the `reader`,
    // if it is not a bigint, try to decode all other values:
    return super.readAny();
  }
```

**Comment by anymos** [comment]
Awesome :) thank you

**Comment by anymos** [comment]
I believe it can be closed, will try and revert back if any other pb .

Thank you again !
