### ISSUE TITLE
`OpReplace` requires a non-standard 'oldValue', but shouldn't

### ISSUE THREAD

**Issue by datner** [streamich/json-joy#781]
The signature of `new OpReplace` is as such
```ts
new OpReplace(path: Path, value: unknown, oldValue: unknown): OpReplace
```
But the json-patch spec [does not mention such a value](https://datatracker.ietf.org/doc/html/rfc6902#section-4.3).
I understand its providing some more advanced behavior, and thats fine. But looking at the implementation it is not expected to exist, it is optional
![CleanShot 2024-11-20 at 21 53 45](https://github.com/user-attachments/assets/da3a5112-7e38-467c-9e61-48156c13bc9e)

I can obviously pass `undefined` explicitly
```ts
new OpReplace(["foo"], value: foo, oldValue: undefined)
```
but it should just be made optional in my opinion.

There are probably other instances of this kind of api

EDIT: yes, all the api is like this

**Comment by streamich** [comment]
It is done this way because, passing it explicitly should be more performant (the `OpReplace` constructor will always receive 3 arguments).
