### ISSUE TITLE
Using a schema breaks str RGA example

### ISSUE THREAD

**Issue by sgpinkus** [streamich/json-joy#782]
v17.20.0.

I copied the [concurrent user example](https://jsonjoy.com/libs/json-joy-js/json-crdt/guide/concurrent-users) from the docs word for word, except for replacing the import paths (which don't work) and changing `withLogicalClock()` to `create()` since the former is apparently deprecated. It gives the correct result every time AFAICT. Then I added a schema, changing the model initialization from this:

```
// Start a new document
const user1 = Model.create();

// Set the initial state of the document
user1.api.root({
  format: 'markdown',
  text: 'Hello!',
});
```

To this:

```
let user1 = Model.create(s.obj({
  format: s.con('markdown'),
  text: s.str('Hello!'),
}));
```
Now the patches sometimes (about 50% of the time) don't give the same result:

```
$ node src/sync.mjs 
{ format: 'markdown', text: 'Hello!' }
{ format: 'markdown', text: 'Hello Alice!' }
{ format: 'markdown', text: 'Hello Charlie!' }
{ format: 'markdown', text: 'Hello Alice Charlie!' }
{ format: 'markdown', text: 'Hello Charlie Alice!' }
```

Full test code:

```
import { Model } from 'json-joy/lib/json-crdt/index.js';
import { Patch } from 'json-joy/lib/json-crdt-patch/index.js';
import {s} from 'json-joy/lib/json-crdt-patch/index.js';

let user1 = Model.create(s.obj({
  format: s.con('markdown'),
  text: s.str('Hello!'),
}));

console.log(user1.view());
// {format: "markdown", text: "Hello!"}

// Serialize the document and send it to another user
const blob = user1.toBinary();

// The other user loads the document and creates a "fork"
// of it, so that a new session ID is assigned
const user2 = Model.fromBinary(blob).fork();

// Now both users insert concurrently some text at
// the same position
user1.api.str(['text']).ins(5, ' Alice');
user2.api.str(['text']).ins(5, ' Charlie');

// We now verify that documents of both users are different
console.log(user1.view()); // {format: "markdown", text: "Hello Alice!"}
console.log(user2.view()); // {format: "markdown", text: "Hello Charlie!"}
// Users can now compute the patches of their changes
const patch1 = user1.api.flush().toBinary();
const patch2 = user2.api.flush().toBinary();

// Users can exchange patches and apply them
user1.applyPatch(Patch.fromBinary(patch2));
user2.applyPatch(Patch.fromBinary(patch1));

// Now both documents converge to the same state
console.log(user1.view()); // {format: "markdown", text: "Hello Charlie Alice!"}
console.log(user2.view()); // {format: "markdown", text: "Hello Charlie Alice!"}
```

**Comment by streamich** [comment]
Thank you for the report and reproduction case!

---

It happens because the initial schema patch is not flushed, it remains in the buffer. In `user1`. Hence the new operations (insertion of `" Alice"`) is appended to that patch in the buffer. Each patch has only one session ID, so it reuses the session ID of the schema `2` instead of the session ID of the `user1`, which is randomly generated on `Mode.create(...)` call.

The quick fix here is to run flush, immediately after `Model.create(..)`:

```ts
user1.api.flush();
```

---

For a proper solution, I'll take a look. I think the `Model.create()` call should just flush automatically, or something like that.

**Comment by streamich** [comment]
I guess for now developers have to manually call `.api.flush()` immediately, if there are patches applied synchronously immediately after.

In the real world it might not be an issues, as new changes will not be applied in the same tick, and there will be some loop setup (for example, model.api.autoFlush()), which automatically flushes patches periodically.

Alternatively, this could be solved by making `.api.flush(): Patch[]` return a list of patches. Where patches are grouped by session ID. But that is too much overhead for such an edge case.
